### ISSUE TITLE
PyPi upload ready?

### ISSUE THREAD

**Issue by ddxtanx** [dsdiscovery/jupyter2pytest#1]
Using this issue to track whether or not this package is ready to be upload to pip.

**Comment by wadefagen** [comment]
Code looks great to me! 🎉 

A few questions:
1. I assume that updating it on PyPi is relatively straightforward?  If it is a little complex, it may be worth waiting until July to do this to make sure we don't want more changes incorporated as we build out the end-of-unit projects/etc?
2. Who can make the updates, and can there be multiple "owners"?  I want to make sure I can still update this even after you graduate and I don't know the access control policies around pushing updates to PyPl?  Can you look into how that's managed?

**Comment by ddxtanx** [comment]
1. From what I understand it's insanely easy - build the wheel/egg with `python3 -m build` and upload it with twine.
2. For access, I'll take a look at how control can be granted rq

**Comment by ddxtanx** [comment]
2. I can easily make anyone with a PyPi account an owner or maintainer - so I could give your account owner access and you could dole out maintainer access to whoever maintains this in the future!

**Comment by wadefagen** [comment]
Perfect -- I just created my account as `wadefagen`.  Thanks for checking on this! 🎉 

LGTM to publish. :)

**Comment by ddxtanx** [comment]
And I just added you as an owner!
